// Image dataset for Real or AI?
// Add or remove entries below — the game picks a balanced set per round.
// All images sourced from Wikimedia Commons under free licenses (public domain / CC).

const IMAGES = [
  // ========== AI-generated ==========
  { src: "images/ai/hedgehog.jpg",           isAI: true,  alt: "Hedgehog",          caption: "AI-generated hedgehog" },
  { src: "images/ai/arctic_wolf.png",        isAI: true,  alt: "Arctic wolf",       caption: "AI-generated — Recraft v3" },
  { src: "images/ai/wolf_moon.jpg",          isAI: true,  alt: "Wolf",              caption: "AI-generated wolf scene" },
  { src: "images/ai/dragon_sunset.png",      isAI: true,  alt: "Dragon at sunset",  caption: "AI-generated — FLUX 1.1 Pro Ultra" },
  { src: "images/ai/moonlit_forest.jpg",     isAI: true,  alt: "Moonlit forest",    caption: "AI-generated — ChatGPT" },
  { src: "images/ai/cold_mountains.jpg",     isAI: true,  alt: "Mountains",         caption: "AI-generated landscape" },
  { src: "images/ai/firefly_landscape.jpg",  isAI: true,  alt: "Landscape",         caption: "AI-generated — Adobe Firefly" },
  { src: "images/ai/fusion_island.png",      isAI: true,  alt: "Island",            caption: "AI-generated island — ChatGPT" },
  { src: "images/ai/ai_food_dish.jpg",       isAI: true,  alt: "Food dish",         caption: "AI-generated food dish" },
  { src: "images/ai/green_apple.png",        isAI: true,  alt: "Green apple",       caption: "AI-generated apple" },
  { src: "images/ai/nun_butterfly.png",      isAI: true,  alt: "Nun and butterfly", caption: "AI-generated — Microsoft Copilot" },
  { src: "images/ai/elderly_lady.png",       isAI: true,  alt: "Elderly lady",      caption: "AI-generated portrait — Copilot" },
  { src: "images/ai/controlnet_portrait.png",isAI: true,  alt: "Portrait",          caption: "AI-generated — ControlNet / Stable Diffusion" },
  { src: "images/ai/frulli_frulla.jpg",      isAI: true,  alt: "Creature",          caption: "AI-generated creature" },
  { src: "images/ai/dalle_writer.webp",      isAI: true,  alt: "Writer illustration", caption: "AI-generated — DALL-E" },
  { src: "images/ai/grok_library.jpg",       isAI: true,  alt: "Library",           caption: "AI-generated library — Grok" },
  { src: "images/ai/street_scene.jpg",       isAI: true,  alt: "Street scene",      caption: "AI-generated street scene — Blockade Labs" },

  // ========== Real photos ==========
  { src: "images/real/leopard.jpg",          isAI: false, alt: "Leopard",           caption: "Real photo — Featured Picture on Commons" },
  { src: "images/real/rainbow.jpg",          isAI: false, alt: "Rainbow",           caption: "Real photo — Yorkshire, UK" },
  { src: "images/real/viaduct.jpg",          isAI: false, alt: "Viaduct",           caption: "Real photo — Ribblehead Viaduct, UK" },
  { src: "images/real/big_mac.jpg",          isAI: false, alt: "Hamburger",         caption: "Real photo — Big Mac hamburger" },
  { src: "images/real/apple_cake.jpg",       isAI: false, alt: "Apple cake",        caption: "Real photo — apple cake with ice cream" },
  { src: "images/real/bleu_de_gex.jpg",      isAI: false, alt: "Cheese",            caption: "Real photo — Bleu de Gex cheese" },
  { src: "images/real/beetroots.jpg",        isAI: false, alt: "Beetroots",         caption: "Real photo — beetroots in a basket" },
  { src: "images/real/asparagus_soup.jpg",   isAI: false, alt: "Asparagus soup",    caption: "Real photo — asparagus soup" },
  { src: "images/real/flower_butterfly.jpg", isAI: false, alt: "Flower",            caption: "Real photo — flower with butterfly" },
  { src: "images/real/swaledale.jpg",        isAI: false, alt: "Swaledale",         caption: "Real photo — Swaledale, UK" },
  { src: "images/real/yorkshire_road.jpg",   isAI: false, alt: "Country road",      caption: "Real photo — Yorkshire Dales" },
  { src: "images/real/grilled_trout.jpg",    isAI: false, alt: "Grilled trout",     caption: "Real photo — grilled trout" },
  { src: "images/real/coral.jpg",            isAI: false, alt: "Coral",             caption: "Real photo — ascidian on soft coral" },
  { src: "images/real/shrimp_shells.jpg",    isAI: false, alt: "Shrimp shells",     caption: "Real photo — shrimp shells on plate" },

  // ========== Real artworks (not AI!) ==========
  { src: "images/real/starry_night.jpg",     isAI: false, alt: "The Starry Night",           caption: "Real — Van Gogh, 'The Starry Night' (1889)" },
  { src: "images/real/mona_lisa.jpg",        isAI: false, alt: "Mona Lisa",                  caption: "Real — Leonardo da Vinci, 'Mona Lisa' (c. 1503)" },
  { src: "images/real/great_wave.jpg",       isAI: false, alt: "Great Wave off Kanagawa",    caption: "Real — Hokusai, 'The Great Wave off Kanagawa' (c. 1831)" },
  { src: "images/real/sunflowers.jpg",       isAI: false, alt: "Sunflowers",                 caption: "Real — Van Gogh, 'Sunflowers' (1888)" },
  { src: "images/real/klimt_kiss.jpg",       isAI: false, alt: "The Kiss",                   caption: "Real — Gustav Klimt, 'The Kiss' (1907–08)" },
  { src: "images/real/american_gothic.jpg",  isAI: false, alt: "American Gothic",            caption: "Real — Grant Wood, 'American Gothic' (1930)" },
  { src: "images/real/pearl_earring.jpg",    isAI: false, alt: "Girl with a Pearl Earring",  caption: "Real — Vermeer, 'Girl with a Pearl Earring' (c. 1665)" },
  { src: "images/real/bosch_garden.jpg",     isAI: false, alt: "Garden of Earthly Delights", caption: "Real — Hieronymus Bosch, 'The Garden of Earthly Delights'" },
  { src: "images/real/monet_sunrise.jpg",    isAI: false, alt: "Impression, Sunrise",        caption: "Real — Monet, 'Impression, Sunrise' (1872)" },
  { src: "images/real/birth_of_venus.jpg",   isAI: false, alt: "The Birth of Venus",         caption: "Real — Botticelli, 'The Birth of Venus' (c. 1485)" },
  { src: "images/real/tower_babel.jpg",      isAI: false, alt: "Tower of Babel",             caption: "Real — Bruegel, 'The Tower of Babel' (1563)" },

  // ========== Real — architecture & places ==========
  { src: "images/real/antwerp_station.jpg",   isAI: false, alt: "Antwerp Central Station", caption: "Real photo — Antwerp Central Station" },
  { src: "images/real/atomium.jpg",           isAI: false, alt: "Atomium",                 caption: "Real photo — Atomium, Brussels" },
  { src: "images/real/scar_house_dam.jpg",    isAI: false, alt: "Reservoir dam",           caption: "Real photo — Scar House Reservoir Dam, UK" },
  { src: "images/real/santorini.jpg",         isAI: false, alt: "Santorini",               caption: "Real photo — Santorini, Greece" },
  { src: "images/real/chefchaouen.jpg",       isAI: false, alt: "Chefchaouen blue city",   caption: "Real photo — Chefchaouen, Morocco" },
  { src: "images/real/ferris_wheel.jpg",      isAI: false, alt: "Ferris wheel",            caption: "Real photo — Daikanransha Ferris wheel, Tokyo" },
  { src: "images/real/brooklyn_garden.jpg",   isAI: false, alt: "Brooklyn Botanic Garden", caption: "Real photo — Brooklyn Botanic Garden" },
  { src: "images/real/belem_docas.jpg",       isAI: false, alt: "Belém, Brazil",           caption: "Real photo — Belém, Brazil" },
  { src: "images/real/brighton_pier.jpg",     isAI: false, alt: "Brighton West Pier",      caption: "Real photo — Brighton West Pier, UK" },
  { src: "images/real/duisburg_park.jpg",     isAI: false, alt: "Industrial park",         caption: "Real photo — Landschaftspark Duisburg-Nord" },

  // ========== Real — nature & wildlife ==========
  { src: "images/real/kagu_bird.jpg",         isAI: false, alt: "Kagu bird",               caption: "Real photo — Kagu bird" },
  { src: "images/real/tropicbird.jpg",        isAI: false, alt: "Tropicbird",              caption: "Real photo — Red-billed tropicbird" },
  { src: "images/real/mantis_nymph.jpg",      isAI: false, alt: "Mantis nymph",            caption: "Real photo — Chinese mantis nymph" },
  { src: "images/real/wheelbug_wasp.jpg",     isAI: false, alt: "Wheel bug and wasp",      caption: "Real photo — wheel bug and paper wasp" },
  { src: "images/real/goose_feather_dew.jpg", isAI: false, alt: "Feather with dew",        caption: "Real photo — goose feather with dew" },
  { src: "images/real/sunrise_field.jpg",     isAI: false, alt: "Sunrise over field",      caption: "Real photo — sunrise over field" },
  { src: "images/real/salar_uyuni.jpg",       isAI: false, alt: "Salar de Uyuni",          caption: "Real photo — Salar de Uyuni, Bolivia" },

  // ========== Real — astronomy ==========
  { src: "images/real/deep_sky.jpg",          isAI: false, alt: "Deep sky",                caption: "Real photo — deep-sky astrophotography" },
  { src: "images/real/moonlight.jpg",         isAI: false, alt: "Moonlight",               caption: "Real photo — moonlight" },

  // ========== Real — people & sports ==========
  { src: "images/real/climbing.jpg",          isAI: false, alt: "Climber",                 caption: "Real photo — Climbing World Championships 2018" },
  { src: "images/real/crack_climbing.jpg",    isAI: false, alt: "Crack climbing",          caption: "Real photo — crack climbing, Indian Creek, Utah" },
  { src: "images/real/swim_butterfly.jpg",    isAI: false, alt: "Butterfly stroke",        caption: "Real photo — competitive swimming, butterfly" },
  { src: "images/real/gymnastics.jpg",        isAI: false, alt: "Olympic gymnastics",      caption: "Real photo — Olympic gymnastics, Rio 2016" },
  { src: "images/real/tractor_laos.jpg",      isAI: false, alt: "Tractor at sunset",       caption: "Real photo — farmer plowing at sunset, Laos" },

  // ========== Real — vehicles / industry ==========
  { src: "images/real/bulldozer.jpg",         isAI: false, alt: "Bulldozer",               caption: "Real photo — Komatsu bulldozer at power plant" },
  { src: "images/real/horse_sleighs.jpg",     isAI: false, alt: "Horse-drawn sleighs",     caption: "Real photo — horse-drawn sleighs" },

  // === AI auto-generated (do not hand-edit this block) ===
  { src: "images/ai/ai_portrait_farmer.jpg", isAI: true, alt: "ai_portrait_farmer", caption: "AI-generated — Z-Image photorealistic portrait" },
  { src: "images/ai/ai_portrait_child_market.jpg", isAI: true, alt: "ai_portrait_child_market", caption: "AI-generated — Z-Image photorealistic portrait" },
  { src: "images/ai/ai_portrait_musician.jpg", isAI: true, alt: "ai_portrait_musician", caption: "AI-generated — Z-Image photorealistic portrait" },
  { src: "images/ai/ai_landscape_coast.jpg", isAI: true, alt: "ai_landscape_coast", caption: "AI-generated — Z-Image landscape" },
  { src: "images/ai/ai_landscape_desert.jpg", isAI: true, alt: "ai_landscape_desert", caption: "AI-generated — Z-Image landscape" },
  { src: "images/ai/ai_landscape_autumn.jpg", isAI: true, alt: "ai_landscape_autumn", caption: "AI-generated — Z-Image landscape" },
  { src: "images/ai/ai_food_ramen.jpg", isAI: true, alt: "ai_food_ramen", caption: "AI-generated — Z-Image food photograph" },
  { src: "images/ai/ai_food_breakfast.jpg", isAI: true, alt: "ai_food_breakfast", caption: "AI-generated — Z-Image food photograph" },
  { src: "images/ai/ai_food_market.jpg", isAI: true, alt: "ai_food_market", caption: "AI-generated — Z-Image food photograph" },
  { src: "images/ai/ai_food_bakery.jpg", isAI: true, alt: "ai_food_bakery", caption: "AI-generated — Z-Image food photograph" },
  { src: "images/ai/ai_animal_fox.jpg", isAI: true, alt: "ai_animal_fox", caption: "AI-generated — Z-Image wildlife photograph" },
  { src: "images/ai/ai_animal_macaw.jpg", isAI: true, alt: "ai_animal_macaw", caption: "AI-generated — Z-Image wildlife photograph" },
  { src: "images/ai/ai_animal_otter.jpg", isAI: true, alt: "ai_animal_otter", caption: "AI-generated — Z-Image wildlife photograph" },
  { src: "images/ai/ai_macro_butterfly.jpg", isAI: true, alt: "ai_macro_butterfly", caption: "AI-generated — Z-Image macro photograph" },
  { src: "images/ai/ai_macro_dewdrop.jpg", isAI: true, alt: "ai_macro_dewdrop", caption: "AI-generated — Z-Image macro photograph" },
  { src: "images/ai/ai_architecture_cathedral.jpg", isAI: true, alt: "ai_architecture_cathedral", caption: "AI-generated — Z-Image architecture photograph" },
  { src: "images/ai/ai_architecture_cabin.jpg", isAI: true, alt: "ai_architecture_cabin", caption: "AI-generated — Z-Image architecture photograph" },
  { src: "images/ai/ai_architecture_alley.jpg", isAI: true, alt: "ai_architecture_alley", caption: "AI-generated — Z-Image architecture photograph" },
  { src: "images/ai/ai_storefront_bookshop.jpg", isAI: true, alt: "ai_storefront_bookshop", caption: "AI-generated — Z-Image storefront photograph" },
  { src: "images/ai/ai_sports_cyclist.jpg", isAI: true, alt: "ai_sports_cyclist", caption: "AI-generated — Z-Image sports photograph" },
  { src: "images/ai/ai_sports_surfer.jpg", isAI: true, alt: "ai_sports_surfer", caption: "AI-generated — Z-Image sports photograph" },
  { src: "images/ai/ai_vehicle_oldcar.jpg", isAI: true, alt: "ai_vehicle_oldcar", caption: "AI-generated — Z-Image vehicle photograph" },
  { src: "images/ai/ai_vehicle_train.jpg", isAI: true, alt: "ai_vehicle_train", caption: "AI-generated — Z-Image vehicle photograph" },
  { src: "images/ai/ai_astro_milkyway.jpg", isAI: true, alt: "ai_astro_milkyway", caption: "AI-generated — Z-Image astrophotography" },
  { src: "images/ai/ai_astro_aurora.jpg", isAI: true, alt: "ai_astro_aurora", caption: "AI-generated — Z-Image astrophotography" },
  { src: "images/ai/ai_street_tokyo.jpg", isAI: true, alt: "ai_street_tokyo", caption: "AI-generated — Z-Image street photograph" },
  { src: "images/ai/ai_street_diner.jpg", isAI: true, alt: "ai_street_diner", caption: "AI-generated — Z-Image street photograph" },
  { src: "images/ai/ai_street_market.jpg", isAI: true, alt: "ai_street_market", caption: "AI-generated — Z-Image street photograph" },
  { src: "images/ai/ai_art_impressionist_harbor.jpg", isAI: true, alt: "ai_art_impressionist_harbor", caption: "AI-generated — Z-Image painting pastiche" },
  { src: "images/ai/ai_art_postimpressionist_field.jpg", isAI: true, alt: "ai_art_postimpressionist_field", caption: "AI-generated — Z-Image painting pastiche" },
  { src: "images/ai/ai_art_ukiyoe_mountain.jpg", isAI: true, alt: "ai_art_ukiyoe_mountain", caption: "AI-generated — Z-Image painting pastiche" },
  { src: "images/ai/ai_art_renaissance_portrait.jpg", isAI: true, alt: "ai_art_renaissance_portrait", caption: "AI-generated — Z-Image painting pastiche" },
  { src: "images/ai/ai_art_dutch_still_life.jpg", isAI: true, alt: "ai_art_dutch_still_life", caption: "AI-generated — Z-Image painting pastiche" },
  { src: "images/ai/ai_art_watercolor_cottage.jpg", isAI: true, alt: "ai_art_watercolor_cottage", caption: "AI-generated — Z-Image painting pastiche" },
  { src: "images/ai/ai_art_abstract_expressionist.jpg", isAI: true, alt: "ai_art_abstract_expressionist", caption: "AI-generated — Z-Image painting pastiche" },
  // === end AI auto-generated ===
];
